version: '3.8'

services:
  # Base de donn√©es MongoDB
  mongodb:
    image: mongo:latest
    container_name: blog_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  # Backend (Node.js/Express)
  backend:
    build: ./backend
    container_name: blog_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/blogdb
      - JWT_SECRET=docker_secret_key_change_me
    depends_on:
      - mongodb

  # Frontend (React/Nginx)
  frontend:
    build: ./blogtester-frontend
    container_name: blog_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
